esphome:
  name: "esp-sps30"

esp32:
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-SPS30 Fallback Hotspot"
    password: !secret wifi_fallback_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: false
    continuous: true

bluetooth_proxy:
  active: true

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true
    frequency: 100kHz

# Example configuration entry
sensor:
  - platform: sps30
    i2c_id: bus_a
    pm_1_0:
      name: "PM1.0"
      id: "PM_1_0"
    pm_2_5:
      name: "PM2.5"
      id: "PM_2_5"
    pm_4_0:
      name: "PM4.0"
      id: "PM_4_0"
    pm_10_0:
      name: "PM10"
      id: "PM_10_0"
    pmc_0_5:
      name: "PMC0.5"
      id: "PMC_0_5"
    pmc_1_0:
      name: "PMC1.0"
      id: "PMC_1_0"
    pmc_2_5:
      name: "PMC2.5"
      id: "PMC_2_5"
    pmc_4_0:
      name: "PMC4.0"
      id: "PMC_4_0"
    pmc_10_0:
      name: "PMC10"
      id: "PMC_10_0"
    pm_size:
      name: "Typical Particle size"
      id: "pm_size"
    address: 0x69
    update_interval: 10s
